language: python

python:
  - 2.7

sudo: false

install:
  - pip install flake8
  - pip install tox
  - pip install coveralls

before_script:
  - flake8 --max-line-length=100 --exclude=tests locking

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py27-django18-grappelli
  - TOXENV=py34-django18-grappelli

script:
  - travis_retry tox

after_success:
  coveralls
